#format = '$all'

# Which is equivalent to
#format = """
#$username\
#$hostname\
#$localip\
#$shlvl\
#$singularity\
#$kubernetes\
#$directory\
#$vcsh\
#$fossil_branch\
#$git_branch\
#$git_commit\
#$git_state\
#$git_metrics\
#$git_status\
#$hg_branch\
#$pijul_channel\
#$docker_context\
#$package\
#$c\
#$cmake\
#$cobol\
#$daml\
#$dart\
#$deno\
#$dotnet\
#$elixir\
#$elm\
#$erlang\
#$fennel\
#$golang\
#$guix_shell\
#$haskell\
#$haxe\
#$helm\
#$java\
#$julia\
#$kotlin\
#$gradle\
#$lua\
#$nim\
#$nodejs\
#$ocaml\
#$opa\
#$perl\
#$php\
#$pulumi\
#$purescript\
#$python\
#$raku\
#$rlang\
#$red\
#$ruby\
#$rust\
#$scala\
#$solidity\
#$swift\
#$terraform\
#$vlang\
#$vagrant\
#$zig\
#$buf\
#$nix_shell\
#$conda\
#$meson\
#$spack\
#$memory_usage\
#$aws\
#$gcloud\
#$openstack\
#$azure\
#$env_var\
#$crystal\
#$custom\
#$sudo\
#$cmd_duration\
#$line_break\
#$jobs\
#$battery\
#$time\
#$status\
#$os\
#$container\
#$shell\
#$character"""

#format = """
#[░▒▓](#a3aed2)\
#[  ](bg:#a3aed2 fg:#090c0c)\
#[](bg:#769ff0 fg:#a3aed2)\
#$directory\
#[](fg:#769ff0 bg:#394260)\
#$git_branch\
#$git_status\
#[](fg:#394260 bg:#212736)\
#$nodejs\
#$rust\
#$golang\
#$php\
#[](fg:#212736 bg:#1d2230)\
#$time\
#[ ](fg:#1d2230)\
#\n$character"""

continuation_prompt = '▶▶ '

format = """
[\ue0b6](fg:#212736)\
[$time](fg:#212736 bg:#1d2230)\
\ue0b2\
$os\
[\ue0b2](bg:#e4e4e4 fg:#073278)\
[ $username @ $hostname ](bg:#073278 fg:#e4e4e4)\
[\ue0b0](bg:#3465a4 fg:#073278)\
$directory\
[\ue0b0](bg:#073278 fg:#3465a4)\
$shell\
[\ue0b0](bg:#4e9a06 fg:#073278)\
$git_branch\
$git_status\
[\ue0b0](bg:#212736 fg:#4e9a06)\
[\ue0b0](bg:#212736 fg:#394260)\
$nodejs\
$rust\
$golang\
$php\
[\ue0b0](bg:#1d2230 fg:#212736)\
$status\
$cmd_duration\
[\ue0b4 ](fg:#1d2230)
$character"""

[cmd_duration]
format = "[:](bg:#1d2230 fg:#212736)[ $duration ]($style)"
min_time = 200
show_milliseconds = true
style = "fg:#9b9b9b bg:#1d2230"

[directory]
style = "bg:#3465a4 fg:#e4e4e4"
format = "[  $path ]($style)"
truncate_to_repo = false
truncation_length = 0
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#4e9a06 fg:#000000"
format = '[[ $symbol $branch(:$remote_branch) ](bg:#4e9a06 fg:#000000)]($style)'

[git_status]
style = "bg:#4e9a06 fg:#000000"
format = '[[($all_status$ahead_behind )](bg:#4e9a06 fg:#000000)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[hostname]
format = '[$ssh_symbol$hostname]($style)'
ssh_only = false
style = 'bg:#073278 fg:#e4e4e4'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[os]
disabled = false
#format = '[ $symbol$name ]($style)''
format = '[ $symbol ]($style)'
style = "bg:#d3d7cf fg:#000000"

# This is the default symbols table.
[os.symbols]
#Alpaquita = "🔔 "
Alpine = " "          # \uF300
#Amazon = "🙂 "
#Android = "🤖 "
Arch = " "            # \uF303
#Artix = "🎗️ "
CentOS = " "          # \uF304
Debian = " "          # \uF306
#DragonFly = "🐉 "
#Emscripten = "🔗 "
EndeavourOS = " "     # \uF322
Fedora = " "          # \uF30A
FreeBSD = " "         # \uF30C
#Garuda = "🦅 "
Gentoo = " "          # \uF30D
#HardenedBSD = "🛡️ "
Illumos = " "         # \uF326
Linux = " "           # \uF17C
#Mabox = "📦 "
Macos = " "           # \uF179
Manjaro = " "         # \uF312
#Mariner = "🌊 "
#MidnightBSD = "🌘 "
Mint = " "            # \uF30E
#NetBSD = "🚩 "
NixOS = " "           # \uF313
OpenBSD = " "         # \uF328
#OpenCloudOS = "☁️ "
#openEuler = "🦉 "
openSUSE = " "        # \uF314
#OracleLinux = "🦴 "
Pop = " "             # \uF32A
Raspbian = " "        # \uF315
Redhat = " "          # \uF316
RedHatEnterprise = " " # \uF316
#Redox = "🧪 "
#Solus = "⛵ "
SUSE = " "            # \uF314
Ubuntu = " "          # \uF31B
Unknown = "? "
Windows = " "         # \uE62A

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[shell]
bash_indicator = ''
#cmd_indicator = ''
disabled = false
format = '[ $indicator ]($style)'
powershell_indicator = ''
style = "bg:#073278 fg:#e4e4e4"

[status]
disabled = false
format = "[ $signal_name $symbol ]($style)"
map_symbol = true
sigint_symbol = "[✗](bg:#1d2230 fg:#d60202)"
style = "bg:#1d2230"
success_symbol = "[✓](bg:#1d2230 fg:green)"
symbol = "[✗](bg:#1d2230 fg:#d60202)"

[time]
disabled = false
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'
style = "bg:#1d2230"
time_format = "%T  %d-%b-%Y"

[username]
disabled = false
format = '[$user]($style)'
show_always = true
style_root = "bg:#073278 fg:#ffff66"
style_user = "bg:#073278 fg:#e4e4e4"
